# Generated by Django 4.0.5 on 2023-03-15 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_rename_created_at_submission_submitted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='author_bio',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='author_name',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='contact_email',
            field=models.EmailField(default='default', max_length=254),
            preserve_default=False,
        ),
    ]
